name: ytene
favicon: null
layout_spectrum: 0.00181
typography_spectrum: 0.2497
title: Ytene - The New Forest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
